const allPairs = [
    { nepali: "उद्यान", korean: "공원" },
    { nepali: "ढुवानी गर्नु", korean: "나루다" },
    { nepali: "विभाजित हुनु", korean: "나누이다" },
    { nepali: "बाहिर जानु", korean: "나가다" },
    { nepali: "खराब हुनु", korean: "나빠지다" },
    { nepali: "बिताउनु", korean: "너다" },
    { nepali: "छोड्नु", korean: "남기다" },
    { nepali: "बाहिर आउनु", korean: "나오다" },
    { nepali: "रूख लगाउनु", korean: "나무를 신다" },
    { nepali: "लड्नु", korean: "넘어지다" },
    { nepali: "प्रयास गर्नु", korean: "노력하다" },
    { nepali: "खेल्नु/मोज गर्नु", korean: "놀다" },
    { nepali: "घुम्न जानु", korean: "놀러가다" },
    { nepali: "जिस्क्याउनु", korean: "놀리다" },
    { nepali: "बाहिर निकाल्नु", korean: "내다" },
    { nepali: "थिच्नु", korean: "누르다" },
    { nepali: "शर्त लगाउनु", korean: "내기하다" },
    { nepali: "ढुवानी गर्नु", korean: "나르다" },
    { nepali: "सुतेर बस्नु", korean: "눕다" },
    { nepali: "सुताउनु", korean: "눕히다" },
    { nepali: "ढिला हुनु", korean: "늦다" },
    { nepali: "वृद्धि हुनु", korean: "늘다" },
    { nepali: "ओर्लनु", korean: "내리다" },
    { nepali: "हिउँ पर्नु", korean: "눈이 오다/눈이 내리다" },
    { nepali: "हिउँ रोकिनु", korean: "눈이 그치다" },
    { nepali: "जन्म दिनु", korean: "낳다" },
    { nepali: "होचो हुनु", korean: "낮다" },
    { nepali: "पग्लनु", korean: "녹다" },
    { nepali: "पगाल्नु", korean: "녹이다" },
    { nepali: "ढोका ढकढक्याउनु", korean: "노크하다" },
    { nepali: "बुढो हुनु", korean: "늙다" },
    { nepali: "जिर्ण हुनु", korean: "낡다" },
    { nepali: "माछा मार्नु", korean: "낚시하다" },
    { nepali: "मौसम सफा हुनु", korean: "날씨가 맑다" },
    { nepali: "बाकी रहनु", korean: "남다" },
    { nepali: "दौडनु", korean: "달리다" },
    { nepali: "अति गर्नु", korean: "너무하다" },
    { nepali: "खेल्नु/मोज गर्नु", korean: "놀다" },
    { nepali: "निको हुनु", korean: "낫다" },
    { nepali: "चौडा हुनु", korean: "넓다" },
    { nepali: "गाउनु", korean: "노래를 부르다/노래하다" },
    { nepali: "पहेंलो हुनु", korean: "노랗다" },
    { nepali: "सार्वजनिक स्थानमा पिसाब गर्नु", korean: "노상방뇨를 하다" },
    { nepali: "अपरिचित हुनु", korean: "낯설다" },
    { nepali: "परिचित हुनु", korean: "낯익다" },
    { nepali: "गुमाउनु", korean: "놓치다" },
    { nepali: "पोलिनु", korean: "눋다" },
    { nepali: "पसल्नु", korean: "넘치다" },
    { nepali: "खर्च गर्नु", korean: "낭비하다" },
    { nepali: "जोक्र्याइँ गर्नु", korean: "농담하다" },
    { nepali: "तेज हुनु", korean: "날카롭다" },
    { nepali: "आँखा बन्द गर्नु", korean: "눈을 감다" },
    { nepali: "आँखा खोल्नु", korean: "눈을 뜨다" },
    { nepali: "आँसु आउनु", korean: "눈물이 나다" },
    { nepali: "आँसु पुछ्नु", korean: "눈물을 닦다" },
    { nepali: "रेकर्ड गर्नु", korean: "녹음하다" },
    { nepali: "जानु", korean: "가다" },
    { nepali: "हिड्नु", korean: "걷다" },
    { nepali: "लिनु", korean: "갖다" },
    { nepali: "फिर्ता गर्नु", korean: "갚다" },
    { nepali: "छान्नु", korean: "고르다" },
    { nepali: "गएर आउनु", korean: "갔다오다" },
    { nepali: "लिई आउनु", korean: "가져오다" },
    { nepali: "ल्याएर दिनु", korean: "갖다주다" },
    { nepali: "फाल्नु", korean: "갖다 버리다" },
    { nepali: "शान्त हुनु", korean: "가만 있다" },
    { nepali: "हस्तक्षेप गर्नु", korean: "간섭하다" },
    { nepali: "चिन्ता गर्नु", korean: "걱정하다" },
    { nepali: "स्मरण गर्नु", korean: "기억하다" },
    { nepali: "प्रार्थना गर्नु", korean: "기도하다" },
    { nepali: "आशा गर्नु", korean: "기대하다" },
    { nepali: "पाल्नु", korean: "기르다" },
  { "nepali": "गम्भीर/प्रबल हुनु", "korean": "독하다" },
  { "nepali": "पुल तर्नु", "korean": "다리를 건너다" },
  { "nepali": "खुट्टा क्रस गरी बस्नु", "korean": "다리를 꼬고 앉다" },
  { "nepali": "बटन लगाउनु", "korean": "단치를 채우다" },
  { "nepali": "बटन खोल्नु", "korean": "단치를 풀다" },
  { "nepali": "फोहोर हुनु", "korean": "다럽다" },
  { "nepali": "फोहोर गर्नु", "korean": "더렵혀/더럽히다" },
  { "nepali": "भेट्नु", "korean": "만나다" },
  { "nepali": "खानु", "korean": "먹다" },
  { "nepali": "खुवाउनु", "korean": "먹이다" },
  { "nepali": "छुनु/समाउनु", "korean": "만지다" },
  { "nepali": "पिउनु", "korean": "마시다" },
  { "nepali": "बनाउनु", "korean": "만들다" },
  { "nepali": "समाप्त गर्नु", "korean": "마치다" },
  { "nepali": "प्रत्येक", "korean": "마다" },
  { "nepali": "व्यवस्थित गर्नु", "korean": "마조하다" },
  { "nepali": "सुक्नु/सुक्खा हुनु", "korean": "마르다" },
  { "nepali": "सुकाउनु", "korean": "말리다" },
  { "nepali": "भन्नु", "korean": "말하다" },
  { "nepali": "कसैको कुरा सुन्नु", "korean": "말을 듣다" },
  { "nepali": "सही हुनु/प्रहार हुनु", "korean": "맞다" },
  { "nepali": "मिलाउनु", "korean": "맞추다" },
  { "nepali": "अवरुद्ध हुनु", "korean": "막하다" },
  { "nepali": "अवरुद्ध गर्नु", "korean": "막다" },
  { "nepali": "स्वादिलो हुनु", "korean": "맛있다" },
  { "nepali": "स्वाद पाउनु", "korean": "맛어다" },
  { "nepali": "झगडा गर्नु", "korean": "말다툼하다" },
  { "nepali": "जवाफ फर्काउनु", "korean": "말대꾸하다" },
  { "nepali": "स्वच्छ हुनु", "korean": "맑다" },
  { "nepali": "मास्क लगाउनु", "korean": "마스크를 쓰다" },
  { "nepali": "टाउको दुख्नु", "korean": "머리가 아프다" },
  { "nepali": "रोक्नु/रोकिनु", "korean": "멈추다" },
  { "nepali": "अनमना हुनु", "korean": "멍하다" },
  { "nepali": "समय आउनु", "korean": "머지가나다" },
  { "nepali": "अन्तर्वार्ता दिनु", "korean": "면접을 보다" },
  { "nepali": "जम्मा गर्नु", "korean": "모다" },
  { "nepali": "हटाउनु/झिक्नु", "korean": "무다" },
  { "nepali": "सोध्नु", "korean": "물어보다" },
  { "nepali": "मिसाउनु", "korean": "무치다" },
  { "nepali": "बेवास्ता गर्नु", "korean": "무시하다" },
  { "nepali": "गह्रौं हुनु", "korean": "무겁다" },
  { "nepali": "डरलाग्दो हुनु", "korean": "무섭다" },
  { "nepali": "मसाज गर्नु/घस्नु", "korean": "문지르다" },
  { "nepali": "समस्या आउनु", "korean": "문제가 생기다" },
  { "nepali": "समस्या समाधान गर्नु", "korean": "문제를 해결하다" },
  { "nepali": "समस्या समाधान गर्नु", "korean": "문제를 풀다" },
  { "nepali": "सोधपुछ गर्नु", "korean": "문의하다" },
  { "nepali": "थाहा नपाउनु", "korean": "모르다" },
  { "nepali": "संकलन गर्नु", "korean": "모으다" },
  { "nepali": "जम्मा हुनु", "korean": "모이다" },
  { "nepali": "विश्वास गर्नु", "korean": "믿다" },
  { "nepali": "पागल हुनु/प्रभाव पार्नु", "korean": "미치다" },
  { "nepali": "धकेल्नु", "korean": "밀다" },
  { "nepali": "पातलो हुनु/चिप्लो हुनु", "korean": "미끄럽다" },
  { "nepali": "मन नपर्नु", "korean": "밉다/밉워다" },
  { "nepali": "प्लास्टर गर्नु", "korean": "미장하다" },
  { "nepali": "बोक्नु", "korean": "메다" },
  { "nepali": "बाँध्नु", "korean": "매다" },
  { "nepali": "झुन्ड्याउनु", "korean": "매달다" },
  { "nepali": "झुन्डिनु", "korean": "매달리다" },
  { "nepali": "पिरो हुनु", "korean": "맵다" },
  { "nepali": "व्यस्त हुनु", "korean": "바쁘다" },
  { "nepali": "फेर्नु/परिवर्तन गर्नु", "korean": "바꾸다" },
  { "nepali": "फेरिनु/परिवर्तित हुनु", "korean": "바뀌다" },
  { "nepali": "वेवास्ता गर्नु/छोडिदिनु", "korean": "방치하다" },
  { "nepali": "फेला पार्नु", "korean": "발견하다" },
  { "nepali": "आशा गर्नु/चाहना गर्नु", "korean": "바라다" },
  { "nepali": "लगाउनु/ठिक हुनु", "korean": "바르다" },
  { "nepali": "चिप्किनु/लाग्नु", "korean": "발리다" },
  { "nepali": "प्राप्त गर्नु/पाउनु", "korean": "받다" },
  { "nepali": "सिक्नु", "korean": "배우다" },
  { "nepali": "विकास गर्नु/प्रगति गर्नु", "korean": "발전 시키다" },
  { "nepali": "विरोध गर्नु", "korean": "반대하다" },
  { "nepali": "अवरोध गर्नु/डिस्टर्ब गर्नु", "korean": "방해하다" },
  { "nepali": "बेपरवाह हुनु/होस गुमाउनु", "korean": "방심하다" },
  { "nepali": "त्याग्नु/फाल्नु", "korean": "버리다" },
  { "nepali": "उतार्नु", "korean": "벗다" },
  { "nepali": "रोग लाग्नु", "korean": "병이 나다" },
  { "nepali": "रोग निको हुनु", "korean": "병이 낫다" },
  { "nepali": "भित्तो", "korean": "벽이" },
  { "nepali": "रोगीको समाचार लिनु", "korean": "병문안 하다" },
  { nepali: "गम्भीर/प्रबल हुनु", korean: "독하다" },
  { nepali: "पुल तर्नु", korean: "다리를 건너다" },
  { nepali: "खुट्टा क्रस गरी बस्नु", korean: "다리를 꼬고 앉다" },
  { nepali: "बटन लगाउनु", korean: "단치를 채우다" },
  { nepali: "बटन खोल्नु", korean: "단치를 풀다" },
  { nepali: "फोहोर हुनु", korean: "다럽다" },
  { nepali: "फोहोर गर्नु", korean: "더렵혀/더럽히다" },
  { nepali: "भेट्नु", korean: "만나다" },
  { nepali: "खानु", korean: "먹다" },
  { nepali: "खुवाउनु", korean: "먹이다" },
  { nepali: "छुनु/समाउनु", korean: "만지다" },
  { nepali: "पिउनु", korean: "마시다" },
  { nepali: "बनाउनु", korean: "만들다" },
  { nepali: "समाप्त गर्नु", korean: "마치다" },
  { nepali: "प्रत्येक", korean: "마다" },
  { nepali: "व्यवस्थित गर्नु", korean: "마조하다" },
  { nepali: "सुक्नु/सुक्खा हुनु", korean: "마르다" },
  { nepali: "सुकाउनु", korean: "말리다" },
  { nepali: "भन्नु", korean: "말하다" },
  { nepali: "कसैको कुरा सुन्नु", korean: "말을 듣다" },
  { nepali: "सही हुनु/प्रहार हुनु", korean: "맞다" },
  { nepali: "मिलाउनु", korean: "맞추다" },
  { nepali: "अवरुद्ध हुनु", korean: "막하다" },
  { nepali: "अवरुद्ध गर्नु", korean: "막다" },
  { nepali: "स्वादिलो हुनु", korean: "맛있다" },
  { nepali: "स्वाद पाउनु", korean: "맛어다" },
  { nepali: "झगडा गर्नु", korean: "말다툼하다" },
  { nepali: "जवाफ फर्काउनु", korean: "말대꾸하다" },
  { nepali: "स्वच्छ हुनु", korean: "맑다" },
  { nepali: "मास्क लगाउनु", korean: "마스크를 쓰다" },
  { nepali: "टाउको दुख्नु", korean: "머리가 아프다" },
  { nepali: "रोक्नु/रोकिनु", korean: "멈추다" },
  { nepali: "अनमना हुनु", korean: "멍하다" },
  { nepali: "समय आउनु", korean: "머지가나다" },
  { nepali: "अन्तर्वार्ता दिनु", korean: "면접을 보다" },
  { nepali: "जम्मा गर्नु", korean: "모다" },
  { nepali: "हटाउनु/झिक्नु", korean: "무다" },
  { nepali: "सोध्नु", korean: "물어보다" },
  { nepali: "मिसाउनु", korean: "무치다" },
  { nepali: "बेवास्ता गर्नु", korean: "무시하다" },
  { nepali: "गह्रौं हुनु", korean: "무겁다" },
  { nepali: "डरलाग्दो हुनु", korean: "무섭다" },
  { nepali: "मसाज गर्नु/घस्नु", korean: "문지르다" },
  { nepali: "समस्या आउनु", korean: "문제가 생기다" },
  { nepali: "समस्या समाधान गर्नु", korean: "문제를 해결하다" },
  { nepali: "समस्या समाधान गर्नु", korean: "문제를 풀다" },
  { nepali: "सोधपुछ गर्नु", korean: "문의하다" },
  { nepali: "थाहा नपाउनु", korean: "모르다" },
  { nepali: "संकलन गर्नु", korean: "모으다" },
  { nepali: "जम्मा हुनु", korean: "모이다" },
  { nepali: "विश्वास गर्नु", korean: "믿다" },
  { nepali: "पागल हुनु/प्रभाव पार्नु", korean: "미치다" },
  { nepali: "धकेल्नु", korean: "밀다" },
  { nepali: "पातलो हुनु/चिप्लो हुनु", korean: "미끄럽다" },
  { nepali: "मन नपर्नु", korean: "밉다/밉워다" },
  { nepali: "प्लास्टर गर्नु", korean: "미장하다" },
  { nepali: "बोक्नु", korean: "메다" },
  { nepali: "बाँध्नु", korean: "매다" },
  { nepali: "झुन्ड्याउनु", korean: "매달다" },
  { nepali: "झुन्डिनु", korean: "매달리다" },
  { nepali: "पिरो हुनु", korean: "맵다" },
  { nepali: "व्यस्त हुनु", korean: "바쁘다" },
  { nepali: "फेर्नु/परिवर्तन गर्नु", korean: "바꾸다" },
  { nepali: "फेरिनु/परिवर्तित हुनु", korean: "바뀌다" },
  { nepali: "वेवास्ता गर्नु/छोडिदिनु", korean: "방치하다" },
  { nepali: "फेला पार्नु", korean: "발견하다" },
  { nepali: "आशा गर्नु/चाहना गर्नु", korean: "바라다" },
  { nepali: "लगाउनु/ठिक हुनु", korean: "바르다" },
  { nepali: "चिप्किनु/लाग्नु", korean: "발리다" },
  { nepali: "प्राप्त गर्नु/पाउनु", korean: "받다" },
  { nepali: "सिक्नु", korean: "배우다" },
  { nepali: "विकास गर्नु/प्रगति गर्नु", korean: "발전 시키다" },
  { nepali: "विरोध गर्नु", korean: "반대하다" },
  { nepali: "अवरोध गर्नु/डिस्टर्ब गर्नु", korean: "방해하다" },
  { nepali: "बेपरवाह हुनु/होस गुमाउनु", korean: "방심하다" },
  { nepali: "त्याग्नु/फाल्नु", korean: "버리다" },
  { nepali: "उतार्नु", korean: "벗다" },
  { nepali: "रोग लाग्नु", korean: "병이 나다" },
  { nepali: "रोग निको हुनु", korean: "병이 낫다" },
  { nepali: "भित्तो", korean: "벽이" },
  { nepali: "रोगीको समाचार लिनु", korean: "병문안 하다" },
  { nepali: "भिज्नु", korean: "젖다" },
  { nepali: "पस्नु", korean: "마르다" },
  { nepali: "जोड्नु", korean: "조립하다" },
  { nepali: "टुक्र्याउनु", korean: "분해하다" },
  { nepali: "सक्नु", korean: "조이다" },
  { nepali: "खोल्नु", korean: "풀다" },
  { nepali: "उल्लासपूर्ण हुनु", korean: "시끄럽다" },
  { nepali: "शान्त हुनु", korean: "조용하다" },
  { nepali: "संकुचित हुनु", korean: "좁다" },
  { nepali: "व्यापक हुनु", korean: "넓다" },
  { nepali: "चिसो हुनु", korean: "치치다" },
  { nepali: "ताजगी हुनु", korean: "상쾌하다" },
  { nepali: "चिसो हुनु", korean: "차갑다" },
  { nepali: "तातो हुनु", korean: "뜨겁다" },
  { nepali: "सही हुनु", korean: "맞다" },
  { nepali: "गलत हुनु", korean: "틀리다" },
  { nepali: "विश्वास गर्नु", korean: "믿다" },
  { nepali: "धोका दिनु", korean: "배신하다" },
  { nepali: "स्वादिलो हुनु", korean: "맛있다" },
  { nepali: "स्वादविहीन हुनु", korean: "맛없다" },
  { nepali: "व्यस्त हुनु", korean: "바쁘다" },
  { nepali: "फुर्सदिलो हुनु", korean: "한가하다" },
  { nepali: "पठाउनु", korean: "보내다" },
  { nepali: "प्राप्त गर्नु", korean: "받다" },
  { nepali: "भोक लाग्नु", korean: "배고프다" },
  { nepali: "पेट भरिएको हुनु", korean: "배부르다" },
  { nepali: "कम हुनु", korean: "부족하다" },
  { nepali: "पर्याप्त हुनु", korean: "충분하다" },
  { nepali: "विरोध गर्नु", korean: "반대하다" },
  { nepali: "सहयोग गर्नु", korean: "지지하다" },
  { nepali: "मोटा हुनु", korean: "뚱뚱하다" },
  { nepali: "पातलो हुनु", korean: "날씬하다" },
  { nepali: "समान हुनु", korean: "똑같다" },
  { nepali: "फरक हुनु", korean: "다르다" },
  { nepali: "सस्तो हुनु", korean: "싸다" },
  { nepali: "महँगो हुनु", korean: "비싸다" },
  { nepali: "झगडा गर्नु", korean: "싸우다" },
  { nepali: "सुलह गर्नु", korean: "화해하다" },
  { nepali: "जमाउनु", korean: "쌓다" },
  { nepali: "विनाश गर्नु", korean: "허물다" },
  { nepali: "चिसो हुनु", korean: "쌀쌀하다" },
  { nepali: "स्वादिष्ट हुनु", korean: "맛뜻하다" },
  { nepali: "पछ्याउनु", korean: "쫓다" },
  { nepali: "भाग्नु", korean: "달아나다" },
  { nepali: "सजिलो हुनु", korean: "쉽다" },
  { nepali: "गाह्रो हुनु", korean: "어렵다" },
  { nepali: "सफल हुनु", korean: "성공되다" },
  { nepali: "असफल हुनु", korean: "실패되다" },
  { nepali: "धक्केर अगाडि जानु", korean: "새치기 하다" },
  { nepali: "मोटो हुनु", korean: "살찌다" },
  { nepali: "पंक्तिको पर्खाइ गर्नु", korean: "차례를 기다리다" },
  { nepali: "पातलो हुनु", korean: "살빠지다" },
  { nepali: "रोगी हुनु", korean: "아프다" },
  { nepali: "निको हुनु", korean: "낫다" },
  { nepali: "हास्नु", korean: "웃다" },
  { nepali: "रुनु", korean: "울다" },
  { nepali: "हुने", korean: "있다" },
  { nepali: "नहुने", korean: "없다" },
  { nepali: "गुमाउनु", korean: "잃다" },
  { nepali: "पत्ता लगाउनु", korean: "찾다" },
  { nepali: "थाहा हुनु", korean: "알다" },
  { nepali: "थाहा नहुने", korean: "모르다" },
  { nepali: "पल्टिनु", korean: "눕다" },
  { nepali: "पाटो तल गर्नु", korean: "엎드리다" },
  { nepali: "दुःखिलो हुनु", korean: "아련하다" },
  { nepali: "गाढा हुनु", korean: "진하다" },
  { nepali: "खतरा हुनु", korean: "위험하다" },
  { nepali: "सुरक्षित हुनु", korean: "안전하다" },
  { nepali: "साहसी हुनु", korean: "용감하다" },
  { nepali: "सङ्कुचित हुनु", korean: "소심하다" },
  { nepali: "हस्पिटलमा भर्ना हुनु", korean: "입원하다" },
  { nepali: "हस्पिटलबाट बाहिर निस्कनु", korean: "퇴원하다" },
  { nepali: "उचो हुनु", korean: "높다" },
  { nepali: "नीचो हुनु", korean: "낮다" },
  { nepali: "अनजान हुनु", korean: "낯설다" },
  { nepali: "चिनो हुनु", korean: "낯익다" },
  { nepali: "पुरानो हुनु", korean: "낡다" },
  { nepali: "नयाँ हुनु", korean: "새롭다" },
  { nepali: "बर्बाद गर्नु", korean: "낭비하다" },
  { nepali: "बचत गर्नु", korean: "절약하다" },
  { nepali: "धैर्यवान हुनु", korean: "느긋하다" },
  { nepali: "अविचारशील हुनु", korean: "성급하다" },
  { nepali: "बन्द गर्नु", korean: "닫다" },
  { nepali: "खोल्नु", korean: "열다" },
  { nepali: "सहमत हुनु", korean: "동의하다" },
  { nepali: "इन्कार गर्नु", korean: "거부하다" },
  { nepali: "घाइते हुनु", korean: "다치다" },
  { nepali: "ठीक हुनु", korean: "멀쩡하다" },
  { nepali: "स्पष्ट हुनु", korean: "맑다" },
  { nepali: "धुंधलाउनु", korean: "흐리다" },
  { nepali: "सन्तुष्ट हुनु", korean: "만족하다" },
  { nepali: "असन्तुष्ट हुनु", korean: "불만족하다" },
  { nepali: "अस्पष्ट हुनु", korean: "막연하다" },
  { nepali: "स्पष्ट हुनु", korean: "분명하다" },
  { nepali: "धेरै हुनु", korean: "많다" },
  { nepali: "थोरै हुनु", korean: "적다" },
  { nepali: "नोकरीमा प्रवेश गर्नु", korean: "입사하다" },
  { nepali: "नोकरीबाट बाहिर जानु", korean: "퇴사하다" },
  { nepali: "कडा हुनु", korean: "엄격하다" },
  { nepali: "शान्त हुनु", korean: "얌전하다" },
  { nepali: "जित्नु", korean: "이기다" },
  { nepali: "हार्नु", korean: "지다" },
  { nepali: "सुत्नु", korean: "자다" },
  { nepali: "उठ्नु", korean: "일어나다" },
  { nepali: "पक्रिनु", korean: "잡다" },
  { nepali: "छोड्नु", korean: "놓다" },
  { nepali: "सावधान हुनु", korean: "조심하다" },
  { nepali: "लापरवाही गर्नु", korean: "방심하다" },
  { nepali: "गन्दो हुनु", korean: "지저분하다" },
  { nepali: "स्वच्छ हुनु", korean: "깨끗하다" },
  { korean: "바르다", nepali: "लगाउनु/ठिक हुनु" },
  { korean: "발리다", nepali: "चिप्किनु/लाग्नु" },
  { korean: "받다", nepali: "प्राप्त गर्नु/पाउनु" },
  { korean: "배우다", nepali: "सिक्नु" },
  { korean: "발전 시키다", nepali: "विकास गर्नु/प्रगति गर्नु" },
  { korean: "반대하다", nepali: "विरोध गर्नु" },
  { korean: "방해하다", nepali: "अवरोध गर्नु/डिस्टर्ब गर्नु" },
  { korean: "방심하다", nepali: "बेपरवाह हुनु/होस गुमाउनु" },
  { korean: "버리다", nepali: "त्याग्नु/फाल्नु" },
  { korean: "벗다", nepali: "उतार्नु" },
  { korean: "병이 나다", nepali: "रोग लाग्नु" },
  { korean: "병이 낫다", nepali: "रोग निको हुनु" },
  { korean: "보내다", nepali: "पठाउनु" },
  { korean: "보답하다", nepali: "जवाफ दिनु/प्रतिकार गर्नु" },
  { korean: "보다", nepali: "हेर्नु" },
  { korean: "보여주다", nepali: "देखाउनु" },
  { korean: "보이다", nepali: "देखिनु" },
  { korean: "볶다", nepali: "भुट्नु/भुटेर पकाउनु" },
  { korean: "베기다", nepali: "काट्नु/घाँटीमा टेक्नु" },
  { korean: "뵙다", nepali: "भेट्नु (आदर सूचक)" },
  { korean: "부르다", nepali: "बोलाउनु/गाउनु" },
  { korean: "배고프다", nepali: "भोक लाग्नु" },
  { korean: "배부르다", nepali: "पेट भरिनु" },
  { korean: "바람이 불다", nepali: "हावा चल्नु" },
  { korean: "부끄럽다", nepali: "लाज लाग्नु" },
  { korean: "부드럽다", nepali: "नरम हुनु" },
  { korean: "부이다", nepali: "देखिनु/देखाउनु" },
  { korean: "빌리다", nepali: "धेरै गर्नु/धेरै माग्नु" },
  { korean: "빌려주다", nepali: "धेरै दिनु" },
  { korean: "부리러하다", nepali: "कर्मगार प्रयोग गर्नु" },
  { korean: "부자가 되다", nepali: "धनी बन्नु" },
  { korean: "부족하다", nepali: "अभाव हुनु/कम हुनु" },
  { korean: "불가능하다", nepali: "असंभव हुनु" },
  { korean: "불길하다", nepali: "अशुभ हुनु" },
  { korean: "불편하다", nepali: "असजिलो हुनु" },
  { korean: "불이 나다", nepali: "आगो लाग्नु" },
  { korean: "불을 끄다", nepali: "आगो निभाउनु" },
  { korean: "비우다", nepali: "खाली गर्नु" },
  { korean: "비키다", nepali: "बाटो दिनु/सर्नु" },
  { korean: "부딪히다", nepali: "ठोक्किनु/ठक्कर खानु" },
  { korean: "복잡하다", nepali: "जटिल हुनु" },
  { korean: "배달하다", nepali: "वितरण गर्नु" },
  { korean: "분리하다", nepali: "अलग गर्नु/विभाजित गर्नु" },
  { korean: "부탁하다", nepali: "अनुरोध गर्नु" },
  { korean: "보호하다", nepali: "सुरक्षा गर्नु" },
  { korean: "배신하다", nepali: "धोका दिनु" },
  { korean: "복습하다", nepali: "पुनः अध्ययन गर्नु" },
  { korean: "부러뜨리다", nepali: "भाँच्नु" },
  { korean: "부러지다", nepali: "भाँचिनु" },
  { korean: "보관하다", nepali: "सुरक्षित राख्नु/भण्डारण गर्नु" },
  { korean: "사다", nepali: "किन्नु" },
  { korean: "사고팔다", nepali: "किनबेच गर्नु" },
  { korean: "서다", nepali: "उभिनु" },
  { korean: "사라지다", nepali: "हराउनु/अदृश्य हुनु" },
  { korean: "수리하다", nepali: "मर्मत गर्नु" },
  { korean: "신다", nepali: "जूता लगाउनु" },
  { korean: "신발을 신다", nepali: "जूता लगाउनु" },
  { korean: "신발을 벗다", nepali: "जूता खोल्नु" },
  { korean: "살다", nepali: "बसोबास गर्नु/बाँच्नु" },
  { korean: "살리다", nepali: "बचाउनु" },
  { korean: "직다", nepali: "सिधा गर्नु" },
  { korean: "식히다", nepali: "चिसो पार्नु" },
  { korean: "시키다", nepali: "आदेश दिनु/गराउनु" },
  { korean: "시험을 보다", nepali: "परीक्षा दिनु" },
  { korean: "시험을 치다", nepali: "परीक्षा दिनु" },
  { korean: "새다", nepali: "चुहिनु" },
  { korean: "세다", nepali: "गन्नु" },
  { korean: "사진을 찍다", nepali: "फोटो खिच्नु" },
  { korean: "사진을 인화하다", nepali: "फोटो प्रिन्ट गर्नु" },
  { korean: "새기다", nepali: "कुद्नु/कोर्नु" },
  { korean: "새롭다", nepali: "नयाँ हुनु" },
  { korean: "송출하다", nepali: "प्रसारण गर्नु" },
  { korean: "속하다", nepali: "सम्बन्धित हुनु" },
  { korean: "사랑하다", nepali: "माया गर्नु" },
  { korean: "살인하다", nepali: "हत्या गर्नु" },
  { korean: "시작하다", nepali: "सुरु गर्नु" },
  { korean: "실수하다", nepali: "गल्ती गर्नु" },
  { korean: "심심하다", nepali: "दिक्क लाग्नु" },
  { korean: "쉬다", nepali: "आराम गर्नु" },
  { korean: "숨을 쉬다", nepali: "सास फेर्नु" },
  { korean: "쉽다", nepali: "सजिलो हुनु" },
  { korean: "승진하다", nepali: "पदोन्नति हुनु" },
  { korean: "승리하다", nepali: "जित्नु" },
  { korean: "숨다", nepali: "लुक्नु" },
  { korean: "숨기다", nepali: "लुकाउनु" },
  { korean: "소심하다", nepali: "संकोची हुनु" },
  { korean: "사기치다", nepali: "ठगी गर्नु" },
  { korean: "사용하다", nepali: "प्रयोग गर्नु" },
  { korean: "선택하다", nepali: "चयन
